import AddInvoice from './components/AddInvoice'
import Navbar from './components/Navbar'
import './globals.css'

export const metadata = {
  title: 'Invoice App',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-11' >
        <Navbar />
        <main className='px-6 pt-8'>
          <AddInvoice />
        </main>
        {children}
      </body>
    </html>
  )
}
